// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks/interfaces_mock.go -package=rxtspot
//

// Package rxtspot is a generated GoMock package.
package rxtspot

import (
	context "context"
	reflect "reflect"

	v1 "github.com/rackspace-spot/spot-go-sdk/api/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockOrganizationAPI is a mock of OrganizationAPI interface.
type MockOrganizationAPI struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationAPIMockRecorder
	isgomock struct{}
}

// MockOrganizationAPIMockRecorder is the mock recorder for MockOrganizationAPI.
type MockOrganizationAPIMockRecorder struct {
	mock *MockOrganizationAPI
}

// NewMockOrganizationAPI creates a new mock instance.
func NewMockOrganizationAPI(ctrl *gomock.Controller) *MockOrganizationAPI {
	mock := &MockOrganizationAPI{ctrl: ctrl}
	mock.recorder = &MockOrganizationAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationAPI) EXPECT() *MockOrganizationAPIMockRecorder {
	return m.recorder
}

// ListOrganizations mocks base method.
func (m *MockOrganizationAPI) ListOrganizations(ctx context.Context) ([]v1.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizations", ctx)
	ret0, _ := ret[0].([]v1.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizations indicates an expected call of ListOrganizations.
func (mr *MockOrganizationAPIMockRecorder) ListOrganizations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizations", reflect.TypeOf((*MockOrganizationAPI)(nil).ListOrganizations), ctx)
}

// MockCloudspaceAPI is a mkock of CloudspaceAPI interface.
type MockCloudspaceAPI struct {
	ctrl     *gomock.Controller
	recorder *MockCloudspaceAPIMockRecorder
	isgomock struct{}
}

// MockCloudspaceAPIMockRecorder is the mock recorder for MockCloudspaceAPI.
type MockCloudspaceAPIMockRecorder struct {
	mock *MockCloudspaceAPI
}

// NewMockCloudspaceAPI creates a new mock instance.
func NewMockCloudspaceAPI(ctrl *gomock.Controller) *MockCloudspaceAPI {
	mock := &MockCloudspaceAPI{ctrl: ctrl}
	mock.recorder = &MockCloudspaceAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudspaceAPI) EXPECT() *MockCloudspaceAPIMockRecorder {
	return m.recorder
}

// CreateCloudspace mocks base method.
func (m *MockCloudspaceAPI) CreateCloudspace(ctx context.Context, cs v1.CloudSpace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCloudspace", ctx, cs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCloudspace indicates an expected call of CreateCloudspace.
func (mr *MockCloudspaceAPIMockRecorder) CreateCloudspace(ctx, cs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCloudspace", reflect.TypeOf((*MockCloudspaceAPI)(nil).CreateCloudspace), ctx, cs)
}

// DeleteCloudspace mocks base method.
func (m *MockCloudspaceAPI) DeleteCloudspace(ctx context.Context, org, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCloudspace", ctx, org, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCloudspace indicates an expected call of DeleteCloudspace.
func (mr *MockCloudspaceAPIMockRecorder) DeleteCloudspace(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCloudspace", reflect.TypeOf((*MockCloudspaceAPI)(nil).DeleteCloudspace), ctx, org, name)
}

// GetCloudspace mocks base method.
func (m *MockCloudspaceAPI) GetCloudspace(ctx context.Context, org, name string) (*v1.CloudSpace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCloudspace", ctx, org, name)
	ret0, _ := ret[0].(*v1.CloudSpace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCloudspace indicates an expected call of GetCloudspace.
func (mr *MockCloudspaceAPIMockRecorder) GetCloudspace(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCloudspace", reflect.TypeOf((*MockCloudspaceAPI)(nil).GetCloudspace), ctx, org, name)
}

// GetCloudspaceConfig mocks base method.
func (m *MockCloudspaceAPI) GetCloudspaceConfig(ctx context.Context, org, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCloudspaceConfig", ctx, org, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCloudspaceConfig indicates an expected call of GetCloudspaceConfig.
func (mr *MockCloudspaceAPIMockRecorder) GetCloudspaceConfig(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCloudspaceConfig", reflect.TypeOf((*MockCloudspaceAPI)(nil).GetCloudspaceConfig), ctx, org, name)
}

// ListCloudspaces mocks base method.
func (m *MockCloudspaceAPI) ListCloudspaces(ctx context.Context, org string) (*v1.CloudSpaceList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCloudspaces", ctx, org)
	ret0, _ := ret[0].(*v1.CloudSpaceList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCloudspaces indicates an expected call of ListCloudspaces.
func (mr *MockCloudspaceAPIMockRecorder) ListCloudspaces(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCloudspaces", reflect.TypeOf((*MockCloudspaceAPI)(nil).ListCloudspaces), ctx, org)
}

// MockSpotNodePoolAPI is a mock of SpotNodePoolAPI interface.
type MockSpotNodePoolAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSpotNodePoolAPIMockRecorder
	isgomock struct{}
}

// MockSpotNodePoolAPIMockRecorder is the mock recorder for MockSpotNodePoolAPI.
type MockSpotNodePoolAPIMockRecorder struct {
	mock *MockSpotNodePoolAPI
}

// NewMockSpotNodePoolAPI creates a new mock instance.
func NewMockSpotNodePoolAPI(ctrl *gomock.Controller) *MockSpotNodePoolAPI {
	mock := &MockSpotNodePoolAPI{ctrl: ctrl}
	mock.recorder = &MockSpotNodePoolAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotNodePoolAPI) EXPECT() *MockSpotNodePoolAPIMockRecorder {
	return m.recorder
}

// CreateSpotNodePool mocks base method.
func (m *MockSpotNodePoolAPI) CreateSpotNodePool(ctx context.Context, org string, pool v1.SpotNodePool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSpotNodePool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSpotNodePool indicates an expected call of CreateSpotNodePool.
func (mr *MockSpotNodePoolAPIMockRecorder) CreateSpotNodePool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSpotNodePool", reflect.TypeOf((*MockSpotNodePoolAPI)(nil).CreateSpotNodePool), ctx, org, pool)
}

// DeleteSpotNodePool mocks base method.
func (m *MockSpotNodePoolAPI) DeleteSpotNodePool(ctx context.Context, org, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSpotNodePool", ctx, org, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSpotNodePool indicates an expected call of DeleteSpotNodePool.
func (mr *MockSpotNodePoolAPIMockRecorder) DeleteSpotNodePool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSpotNodePool", reflect.TypeOf((*MockSpotNodePoolAPI)(nil).DeleteSpotNodePool), ctx, org, name)
}

// GetSpotNodePool mocks base method.
func (m *MockSpotNodePoolAPI) GetSpotNodePool(ctx context.Context, org, name string) (*v1.SpotNodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpotNodePool", ctx, org, name)
	ret0, _ := ret[0].(*v1.SpotNodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpotNodePool indicates an expected call of GetSpotNodePool.
func (mr *MockSpotNodePoolAPIMockRecorder) GetSpotNodePool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpotNodePool", reflect.TypeOf((*MockSpotNodePoolAPI)(nil).GetSpotNodePool), ctx, org, name)
}

// ListSpotNodePools mocks base method.
func (m *MockSpotNodePoolAPI) ListSpotNodePools(ctx context.Context, org, cloudspace string) ([]*v1.SpotNodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSpotNodePools", ctx, org, cloudspace)
	ret0, _ := ret[0].([]*v1.SpotNodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSpotNodePools indicates an expected call of ListSpotNodePools.
func (mr *MockSpotNodePoolAPIMockRecorder) ListSpotNodePools(ctx, org, cloudspace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSpotNodePools", reflect.TypeOf((*MockSpotNodePoolAPI)(nil).ListSpotNodePools), ctx, org, cloudspace)
}

// UpdateSpotNodePool mocks base method.
func (m *MockSpotNodePoolAPI) UpdateSpotNodePool(ctx context.Context, org string, pool v1.SpotNodePool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSpotNodePool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSpotNodePool indicates an expected call of UpdateSpotNodePool.
func (mr *MockSpotNodePoolAPIMockRecorder) UpdateSpotNodePool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSpotNodePool", reflect.TypeOf((*MockSpotNodePoolAPI)(nil).UpdateSpotNodePool), ctx, org, pool)
}

// MockOnDemandNodePoolAPI is a mock of OnDemandNodePoolAPI interface.
type MockOnDemandNodePoolAPI struct {
	ctrl     *gomock.Controller
	recorder *MockOnDemandNodePoolAPIMockRecorder
	isgomock struct{}
}

// MockOnDemandNodePoolAPIMockRecorder is the mock recorder for MockOnDemandNodePoolAPI.
type MockOnDemandNodePoolAPIMockRecorder struct {
	mock *MockOnDemandNodePoolAPI
}

// NewMockOnDemandNodePoolAPI creates a new mock instance.
func NewMockOnDemandNodePoolAPI(ctrl *gomock.Controller) *MockOnDemandNodePoolAPI {
	mock := &MockOnDemandNodePoolAPI{ctrl: ctrl}
	mock.recorder = &MockOnDemandNodePoolAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOnDemandNodePoolAPI) EXPECT() *MockOnDemandNodePoolAPIMockRecorder {
	return m.recorder
}

// CreateOnDemandNodePool mocks base method.
func (m *MockOnDemandNodePoolAPI) CreateOnDemandNodePool(ctx context.Context, org string, pool v1.OnDemandNodePool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOnDemandNodePool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOnDemandNodePool indicates an expected call of CreateOnDemandNodePool.
func (mr *MockOnDemandNodePoolAPIMockRecorder) CreateOnDemandNodePool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOnDemandNodePool", reflect.TypeOf((*MockOnDemandNodePoolAPI)(nil).CreateOnDemandNodePool), ctx, org, pool)
}

// DeleteOnDemandNodePool mocks base method.
func (m *MockOnDemandNodePoolAPI) DeleteOnDemandNodePool(ctx context.Context, org, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOnDemandNodePool", ctx, org, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOnDemandNodePool indicates an expected call of DeleteOnDemandNodePool.
func (mr *MockOnDemandNodePoolAPIMockRecorder) DeleteOnDemandNodePool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOnDemandNodePool", reflect.TypeOf((*MockOnDemandNodePoolAPI)(nil).DeleteOnDemandNodePool), ctx, org, name)
}

// GetOnDemandNodePool mocks base method.
func (m *MockOnDemandNodePoolAPI) GetOnDemandNodePool(ctx context.Context, org, name string) (*v1.OnDemandNodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOnDemandNodePool", ctx, org, name)
	ret0, _ := ret[0].(*v1.OnDemandNodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOnDemandNodePool indicates an expected call of GetOnDemandNodePool.
func (mr *MockOnDemandNodePoolAPIMockRecorder) GetOnDemandNodePool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOnDemandNodePool", reflect.TypeOf((*MockOnDemandNodePoolAPI)(nil).GetOnDemandNodePool), ctx, org, name)
}

// ListOnDemandNodePools mocks base method.
func (m *MockOnDemandNodePoolAPI) ListOnDemandNodePools(ctx context.Context, org, cloudspace string) ([]*v1.OnDemandNodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOnDemandNodePools", ctx, org, cloudspace)
	ret0, _ := ret[0].([]*v1.OnDemandNodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOnDemandNodePools indicates an expected call of ListOnDemandNodePools.
func (mr *MockOnDemandNodePoolAPIMockRecorder) ListOnDemandNodePools(ctx, org, cloudspace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOnDemandNodePools", reflect.TypeOf((*MockOnDemandNodePoolAPI)(nil).ListOnDemandNodePools), ctx, org, cloudspace)
}

// UpdateOnDemandNodePool mocks base method.
func (m *MockOnDemandNodePoolAPI) UpdateOnDemandNodePool(ctx context.Context, org string, pool v1.OnDemandNodePool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOnDemandNodePool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOnDemandNodePool indicates an expected call of UpdateOnDemandNodePool.
func (mr *MockOnDemandNodePoolAPIMockRecorder) UpdateOnDemandNodePool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOnDemandNodePool", reflect.TypeOf((*MockOnDemandNodePoolAPI)(nil).UpdateOnDemandNodePool), ctx, org, pool)
}

// MockSpotRegionsAPI is a mock of SpotRegionsAPI interface.
type MockSpotRegionsAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSpotRegionsAPIMockRecorder
	isgomock struct{}
}

// MockSpotRegionsAPIMockRecorder is the mock recorder for MockSpotRegionsAPI.
type MockSpotRegionsAPIMockRecorder struct {
	mock *MockSpotRegionsAPI
}

// NewMockSpotRegionsAPI creates a new mock instance.
func NewMockSpotRegionsAPI(ctrl *gomock.Controller) *MockSpotRegionsAPI {
	mock := &MockSpotRegionsAPI{ctrl: ctrl}
	mock.recorder = &MockSpotRegionsAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotRegionsAPI) EXPECT() *MockSpotRegionsAPIMockRecorder {
	return m.recorder
}

// GetRegion mocks base method.
func (m *MockSpotRegionsAPI) GetRegion(ctx context.Context, name string) (*v1.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegion", ctx, name)
	ret0, _ := ret[0].(*v1.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegion indicates an expected call of GetRegion.
func (mr *MockSpotRegionsAPIMockRecorder) GetRegion(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegion", reflect.TypeOf((*MockSpotRegionsAPI)(nil).GetRegion), ctx, name)
}

// ListRegions mocks base method.
func (m *MockSpotRegionsAPI) ListRegions(ctx context.Context) ([]v1.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRegions", ctx)
	ret0, _ := ret[0].([]v1.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRegions indicates an expected call of ListRegions.
func (mr *MockSpotRegionsAPIMockRecorder) ListRegions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRegions", reflect.TypeOf((*MockSpotRegionsAPI)(nil).ListRegions), ctx)
}

// MockSpotServerClassesAPI is a mock of SpotServerClassesAPI interface.
type MockSpotServerClassesAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSpotServerClassesAPIMockRecorder
	isgomock struct{}
}

// MockSpotServerClassesAPIMockRecorder is the mock recorder for MockSpotServerClassesAPI.
type MockSpotServerClassesAPIMockRecorder struct {
	mock *MockSpotServerClassesAPI
}

// NewMockSpotServerClassesAPI creates a new mock instance.
func NewMockSpotServerClassesAPI(ctrl *gomock.Controller) *MockSpotServerClassesAPI {
	mock := &MockSpotServerClassesAPI{ctrl: ctrl}
	mock.recorder = &MockSpotServerClassesAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotServerClassesAPI) EXPECT() *MockSpotServerClassesAPIMockRecorder {
	return m.recorder
}

// GetServerClass mocks base method.
func (m *MockSpotServerClassesAPI) GetServerClass(ctx context.Context, name string) (*v1.ServerClass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerClass", ctx, name)
	ret0, _ := ret[0].(*v1.ServerClass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerClass indicates an expected call of GetServerClass.
func (mr *MockSpotServerClassesAPIMockRecorder) GetServerClass(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerClass", reflect.TypeOf((*MockSpotServerClassesAPI)(nil).GetServerClass), ctx, name)
}

// ListServerClasses mocks base method.
func (m *MockSpotServerClassesAPI) ListServerClasses(ctx context.Context, region string) (*v1.ServerClassList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServerClasses", ctx, region)
	ret0, _ := ret[0].(*v1.ServerClassList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServerClasses indicates an expected call of ListServerClasses.
func (mr *MockSpotServerClassesAPIMockRecorder) ListServerClasses(ctx, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServerClasses", reflect.TypeOf((*MockSpotServerClassesAPI)(nil).ListServerClasses), ctx, region)
}

// MockSpotPricingAPI is a mock of SpotPricingAPI interface.
type MockSpotPricingAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSpotPricingAPIMockRecorder
	isgomock struct{}
}

// MockSpotPricingAPIMockRecorder is the mock recorder for MockSpotPricingAPI.
type MockSpotPricingAPIMockRecorder struct {
	mock *MockSpotPricingAPI
}

// NewMockSpotPricingAPI creates a new mock instance.
func NewMockSpotPricingAPI(ctrl *gomock.Controller) *MockSpotPricingAPI {
	mock := &MockSpotPricingAPI{ctrl: ctrl}
	mock.recorder = &MockSpotPricingAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotPricingAPI) EXPECT() *MockSpotPricingAPIMockRecorder {
	return m.recorder
}

// GetMarketPriceForServerClass mocks base method.
func (m *MockSpotPricingAPI) GetMarketPriceForServerClass(ctx context.Context, serverClass string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMarketPriceForServerClass", ctx, serverClass)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMarketPriceForServerClass indicates an expected call of GetMarketPriceForServerClass.
func (mr *MockSpotPricingAPIMockRecorder) GetMarketPriceForServerClass(ctx, serverClass any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMarketPriceForServerClass", reflect.TypeOf((*MockSpotPricingAPI)(nil).GetMarketPriceForServerClass), ctx, serverClass)
}

// GetMinimumBidPriceForServerClass mocks base method.
func (m *MockSpotPricingAPI) GetMinimumBidPriceForServerClass(ctx context.Context, serverClass string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinimumBidPriceForServerClass", ctx, serverClass)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinimumBidPriceForServerClass indicates an expected call of GetMinimumBidPriceForServerClass.
func (mr *MockSpotPricingAPIMockRecorder) GetMinimumBidPriceForServerClass(ctx, serverClass any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinimumBidPriceForServerClass", reflect.TypeOf((*MockSpotPricingAPI)(nil).GetMinimumBidPriceForServerClass), ctx, serverClass)
}

// GetPriceDetails mocks base method.
func (m *MockSpotPricingAPI) GetPriceDetails(ctx context.Context) ([]*v1.PriceDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceDetails", ctx)
	ret0, _ := ret[0].([]*v1.PriceDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceDetails indicates an expected call of GetPriceDetails.
func (mr *MockSpotPricingAPIMockRecorder) GetPriceDetails(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceDetails", reflect.TypeOf((*MockSpotPricingAPI)(nil).GetPriceDetails), ctx)
}

// GetPriceDetailsForRegion mocks base method.
func (m *MockSpotPricingAPI) GetPriceDetailsForRegion(ctx context.Context, region string) (*v1.PriceDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceDetailsForRegion", ctx, region)
	ret0, _ := ret[0].(*v1.PriceDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceDetailsForRegion indicates an expected call of GetPriceDetailsForRegion.
func (mr *MockSpotPricingAPIMockRecorder) GetPriceDetailsForRegion(ctx, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceDetailsForRegion", reflect.TypeOf((*MockSpotPricingAPI)(nil).GetPriceDetailsForRegion), ctx, region)
}

// GetPriceDetailsForServerClass mocks base method.
func (m *MockSpotPricingAPI) GetPriceDetailsForServerClass(ctx context.Context, serverClass string) (*v1.PriceDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceDetailsForServerClass", ctx, serverClass)
	ret0, _ := ret[0].(*v1.PriceDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceDetailsForServerClass indicates an expected call of GetPriceDetailsForServerClass.
func (mr *MockSpotPricingAPIMockRecorder) GetPriceDetailsForServerClass(ctx, serverClass any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceDetailsForServerClass", reflect.TypeOf((*MockSpotPricingAPI)(nil).GetPriceDetailsForServerClass), ctx, serverClass)
}

// MockSpotAPI is a mock of SpotAPI interface.
type MockSpotAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSpotAPIMockRecorder
	isgomock struct{}
}

// MockSpotAPIMockRecorder is the mock recorder for MockSpotAPI.
type MockSpotAPIMockRecorder struct {
	mock *MockSpotAPI
}

// NewMockSpotAPI creates a new mock instance.
func NewMockSpotAPI(ctrl *gomock.Controller) *MockSpotAPI {
	mock := &MockSpotAPI{ctrl: ctrl}
	mock.recorder = &MockSpotAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotAPI) EXPECT() *MockSpotAPIMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockSpotAPI) Authenticate(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockSpotAPIMockRecorder) Authenticate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockSpotAPI)(nil).Authenticate), ctx)
}

// CreateCloudspace mocks base method.
func (m *MockSpotAPI) CreateCloudspace(ctx context.Context, cs v1.CloudSpace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCloudspace", ctx, cs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCloudspace indicates an expected call of CreateCloudspace.
func (mr *MockSpotAPIMockRecorder) CreateCloudspace(ctx, cs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCloudspace", reflect.TypeOf((*MockSpotAPI)(nil).CreateCloudspace), ctx, cs)
}

// CreateOnDemandNodePool mocks base method.
func (m *MockSpotAPI) CreateOnDemandNodePool(ctx context.Context, org string, pool v1.OnDemandNodePool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOnDemandNodePool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOnDemandNodePool indicates an expected call of CreateOnDemandNodePool.
func (mr *MockSpotAPIMockRecorder) CreateOnDemandNodePool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOnDemandNodePool", reflect.TypeOf((*MockSpotAPI)(nil).CreateOnDemandNodePool), ctx, org, pool)
}

// CreateSpotNodePool mocks base method.
func (m *MockSpotAPI) CreateSpotNodePool(ctx context.Context, org string, pool v1.SpotNodePool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSpotNodePool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSpotNodePool indicates an expected call of CreateSpotNodePool.
func (mr *MockSpotAPIMockRecorder) CreateSpotNodePool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSpotNodePool", reflect.TypeOf((*MockSpotAPI)(nil).CreateSpotNodePool), ctx, org, pool)
}

// DeleteCloudspace mocks base method.
func (m *MockSpotAPI) DeleteCloudspace(ctx context.Context, org, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCloudspace", ctx, org, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCloudspace indicates an expected call of DeleteCloudspace.
func (mr *MockSpotAPIMockRecorder) DeleteCloudspace(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCloudspace", reflect.TypeOf((*MockSpotAPI)(nil).DeleteCloudspace), ctx, org, name)
}

// DeleteOnDemandNodePool mocks base method.
func (m *MockSpotAPI) DeleteOnDemandNodePool(ctx context.Context, org, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOnDemandNodePool", ctx, org, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOnDemandNodePool indicates an expected call of DeleteOnDemandNodePool.
func (mr *MockSpotAPIMockRecorder) DeleteOnDemandNodePool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOnDemandNodePool", reflect.TypeOf((*MockSpotAPI)(nil).DeleteOnDemandNodePool), ctx, org, name)
}

// DeleteSpotNodePool mocks base method.
func (m *MockSpotAPI) DeleteSpotNodePool(ctx context.Context, org, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSpotNodePool", ctx, org, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSpotNodePool indicates an expected call of DeleteSpotNodePool.
func (mr *MockSpotAPIMockRecorder) DeleteSpotNodePool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSpotNodePool", reflect.TypeOf((*MockSpotAPI)(nil).DeleteSpotNodePool), ctx, org, name)
}

// GetCloudspace mocks base method.
func (m *MockSpotAPI) GetCloudspace(ctx context.Context, org, name string) (*v1.CloudSpace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCloudspace", ctx, org, name)
	ret0, _ := ret[0].(*v1.CloudSpace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCloudspace indicates an expected call of GetCloudspace.
func (mr *MockSpotAPIMockRecorder) GetCloudspace(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCloudspace", reflect.TypeOf((*MockSpotAPI)(nil).GetCloudspace), ctx, org, name)
}

// GetCloudspaceConfig mocks base method.
func (m *MockSpotAPI) GetCloudspaceConfig(ctx context.Context, org, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCloudspaceConfig", ctx, org, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCloudspaceConfig indicates an expected call of GetCloudspaceConfig.
func (mr *MockSpotAPIMockRecorder) GetCloudspaceConfig(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCloudspaceConfig", reflect.TypeOf((*MockSpotAPI)(nil).GetCloudspaceConfig), ctx, org, name)
}

// GetMarketPriceForServerClass mocks base method.
func (m *MockSpotAPI) GetMarketPriceForServerClass(ctx context.Context, serverClass string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMarketPriceForServerClass", ctx, serverClass)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMarketPriceForServerClass indicates an expected call of GetMarketPriceForServerClass.
func (mr *MockSpotAPIMockRecorder) GetMarketPriceForServerClass(ctx, serverClass any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMarketPriceForServerClass", reflect.TypeOf((*MockSpotAPI)(nil).GetMarketPriceForServerClass), ctx, serverClass)
}

// GetMinimumBidPriceForServerClass mocks base method.
func (m *MockSpotAPI) GetMinimumBidPriceForServerClass(ctx context.Context, serverClass string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinimumBidPriceForServerClass", ctx, serverClass)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMinimumBidPriceForServerClass indicates an expected call of GetMinimumBidPriceForServerClass.
func (mr *MockSpotAPIMockRecorder) GetMinimumBidPriceForServerClass(ctx, serverClass any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinimumBidPriceForServerClass", reflect.TypeOf((*MockSpotAPI)(nil).GetMinimumBidPriceForServerClass), ctx, serverClass)
}

// GetOnDemandNodePool mocks base method.
func (m *MockSpotAPI) GetOnDemandNodePool(ctx context.Context, org, name string) (*v1.OnDemandNodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOnDemandNodePool", ctx, org, name)
	ret0, _ := ret[0].(*v1.OnDemandNodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOnDemandNodePool indicates an expected call of GetOnDemandNodePool.
func (mr *MockSpotAPIMockRecorder) GetOnDemandNodePool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOnDemandNodePool", reflect.TypeOf((*MockSpotAPI)(nil).GetOnDemandNodePool), ctx, org, name)
}

// GetPriceDetails mocks base method.
func (m *MockSpotAPI) GetPriceDetails(ctx context.Context) ([]*v1.PriceDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceDetails", ctx)
	ret0, _ := ret[0].([]*v1.PriceDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceDetails indicates an expected call of GetPriceDetails.
func (mr *MockSpotAPIMockRecorder) GetPriceDetails(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceDetails", reflect.TypeOf((*MockSpotAPI)(nil).GetPriceDetails), ctx)
}

// GetPriceDetailsForRegion mocks base method.
func (m *MockSpotAPI) GetPriceDetailsForRegion(ctx context.Context, region string) (*v1.PriceDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceDetailsForRegion", ctx, region)
	ret0, _ := ret[0].(*v1.PriceDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceDetailsForRegion indicates an expected call of GetPriceDetailsForRegion.
func (mr *MockSpotAPIMockRecorder) GetPriceDetailsForRegion(ctx, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceDetailsForRegion", reflect.TypeOf((*MockSpotAPI)(nil).GetPriceDetailsForRegion), ctx, region)
}

// GetPriceDetailsForServerClass mocks base method.
func (m *MockSpotAPI) GetPriceDetailsForServerClass(ctx context.Context, serverClass string) (*v1.PriceDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceDetailsForServerClass", ctx, serverClass)
	ret0, _ := ret[0].(*v1.PriceDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceDetailsForServerClass indicates an expected call of GetPriceDetailsForServerClass.
func (mr *MockSpotAPIMockRecorder) GetPriceDetailsForServerClass(ctx, serverClass any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceDetailsForServerClass", reflect.TypeOf((*MockSpotAPI)(nil).GetPriceDetailsForServerClass), ctx, serverClass)
}

// GetRegion mocks base method.
func (m *MockSpotAPI) GetRegion(ctx context.Context, name string) (*v1.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegion", ctx, name)
	ret0, _ := ret[0].(*v1.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegion indicates an expected call of GetRegion.
func (mr *MockSpotAPIMockRecorder) GetRegion(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegion", reflect.TypeOf((*MockSpotAPI)(nil).GetRegion), ctx, name)
}

// GetServerClass mocks base method.
func (m *MockSpotAPI) GetServerClass(ctx context.Context, name string) (*v1.ServerClass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerClass", ctx, name)
	ret0, _ := ret[0].(*v1.ServerClass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerClass indicates an expected call of GetServerClass.
func (mr *MockSpotAPIMockRecorder) GetServerClass(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerClass", reflect.TypeOf((*MockSpotAPI)(nil).GetServerClass), ctx, name)
}

// GetSpotNodePool mocks base method.
func (m *MockSpotAPI) GetSpotNodePool(ctx context.Context, org, name string) (*v1.SpotNodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpotNodePool", ctx, org, name)
	ret0, _ := ret[0].(*v1.SpotNodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpotNodePool indicates an expected call of GetSpotNodePool.
func (mr *MockSpotAPIMockRecorder) GetSpotNodePool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpotNodePool", reflect.TypeOf((*MockSpotAPI)(nil).GetSpotNodePool), ctx, org, name)
}

// ListCloudspaces mocks base method.
func (m *MockSpotAPI) ListCloudspaces(ctx context.Context, org string) (*v1.CloudSpaceList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCloudspaces", ctx, org)
	ret0, _ := ret[0].(*v1.CloudSpaceList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCloudspaces indicates an expected call of ListCloudspaces.
func (mr *MockSpotAPIMockRecorder) ListCloudspaces(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCloudspaces", reflect.TypeOf((*MockSpotAPI)(nil).ListCloudspaces), ctx, org)
}

// ListOnDemandNodePools mocks base method.
func (m *MockSpotAPI) ListOnDemandNodePools(ctx context.Context, org, cloudspace string) ([]*v1.OnDemandNodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOnDemandNodePools", ctx, org, cloudspace)
	ret0, _ := ret[0].([]*v1.OnDemandNodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOnDemandNodePools indicates an expected call of ListOnDemandNodePools.
func (mr *MockSpotAPIMockRecorder) ListOnDemandNodePools(ctx, org, cloudspace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOnDemandNodePools", reflect.TypeOf((*MockSpotAPI)(nil).ListOnDemandNodePools), ctx, org, cloudspace)
}

// ListOrganizations mocks base method.
func (m *MockSpotAPI) ListOrganizations(ctx context.Context) ([]v1.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizations", ctx)
	ret0, _ := ret[0].([]v1.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizations indicates an expected call of ListOrganizations.
func (mr *MockSpotAPIMockRecorder) ListOrganizations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizations", reflect.TypeOf((*MockSpotAPI)(nil).ListOrganizations), ctx)
}

// ListRegions mocks base method.
func (m *MockSpotAPI) ListRegions(ctx context.Context) ([]v1.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRegions", ctx)
	ret0, _ := ret[0].([]v1.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRegions indicates an expected call of ListRegions.
func (mr *MockSpotAPIMockRecorder) ListRegions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRegions", reflect.TypeOf((*MockSpotAPI)(nil).ListRegions), ctx)
}

// ListServerClasses mocks base method.
func (m *MockSpotAPI) ListServerClasses(ctx context.Context, region string) (*v1.ServerClassList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServerClasses", ctx, region)
	ret0, _ := ret[0].(*v1.ServerClassList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServerClasses indicates an expected call of ListServerClasses.
func (mr *MockSpotAPIMockRecorder) ListServerClasses(ctx, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServerClasses", reflect.TypeOf((*MockSpotAPI)(nil).ListServerClasses), ctx, region)
}

// ListSpotNodePools mocks base method.
func (m *MockSpotAPI) ListSpotNodePools(ctx context.Context, org, cloudspace string) ([]*v1.SpotNodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSpotNodePools", ctx, org, cloudspace)
	ret0, _ := ret[0].([]*v1.SpotNodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSpotNodePools indicates an expected call of ListSpotNodePools.
func (mr *MockSpotAPIMockRecorder) ListSpotNodePools(ctx, org, cloudspace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSpotNodePools", reflect.TypeOf((*MockSpotAPI)(nil).ListSpotNodePools), ctx, org, cloudspace)
}

// UpdateOnDemandNodePool mocks base method.
func (m *MockSpotAPI) UpdateOnDemandNodePool(ctx context.Context, org string, pool v1.OnDemandNodePool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOnDemandNodePool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOnDemandNodePool indicates an expected call of UpdateOnDemandNodePool.
func (mr *MockSpotAPIMockRecorder) UpdateOnDemandNodePool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOnDemandNodePool", reflect.TypeOf((*MockSpotAPI)(nil).UpdateOnDemandNodePool), ctx, org, pool)
}

// UpdateSpotNodePool mocks base method.
func (m *MockSpotAPI) UpdateSpotNodePool(ctx context.Context, org string, pool v1.SpotNodePool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSpotNodePool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSpotNodePool indicates an expected call of UpdateSpotNodePool.
func (mr *MockSpotAPIMockRecorder) UpdateSpotNodePool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSpotNodePool", reflect.TypeOf((*MockSpotAPI)(nil).UpdateSpotNodePool), ctx, org, pool)
}
