// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source interfaces.go -destination mocks/mock_interfaces.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	rxtspot "github.com/rackspace-spot/spot-go-sdk/api/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockOrganizationAPI is a mock of OrganizationAPI interface.
type MockOrganizationAPI struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationAPIMockRecorder
	isgomock struct{}
}

// MockOrganizationAPIMockRecorder is the mock recorder for MockOrganizationAPI.
type MockOrganizationAPIMockRecorder struct {
	mock *MockOrganizationAPI
}

// NewMockOrganizationAPI creates a new mock instance.
func NewMockOrganizationAPI(ctrl *gomock.Controller) *MockOrganizationAPI {
	mock := &MockOrganizationAPI{ctrl: ctrl}
	mock.recorder = &MockOrganizationAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationAPI) EXPECT() *MockOrganizationAPIMockRecorder {
	return m.recorder
}

// ListOrganizations mocks base method.
func (m *MockOrganizationAPI) ListOrganizations(ctx context.Context) ([]rxtspot.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizations", ctx)
	ret0, _ := ret[0].([]rxtspot.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizations indicates an expected call of ListOrganizations.
func (mr *MockOrganizationAPIMockRecorder) ListOrganizations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizations", reflect.TypeOf((*MockOrganizationAPI)(nil).ListOrganizations), ctx)
}

// MockCloudspaceAPI is a mock of CloudspaceAPI interface.
type MockCloudspaceAPI struct {
	ctrl     *gomock.Controller
	recorder *MockCloudspaceAPIMockRecorder
	isgomock struct{}
}

// MockCloudspaceAPIMockRecorder is the mock recorder for MockCloudspaceAPI.
type MockCloudspaceAPIMockRecorder struct {
	mock *MockCloudspaceAPI
}

// NewMockCloudspaceAPI creates a new mock instance.
func NewMockCloudspaceAPI(ctrl *gomock.Controller) *MockCloudspaceAPI {
	mock := &MockCloudspaceAPI{ctrl: ctrl}
	mock.recorder = &MockCloudspaceAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudspaceAPI) EXPECT() *MockCloudspaceAPIMockRecorder {
	return m.recorder
}

// CreateCloudspace mocks base method.
func (m *MockCloudspaceAPI) CreateCloudspace(ctx context.Context, cs rxtspot.CloudSpace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCloudspace", ctx, cs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCloudspace indicates an expected call of CreateCloudspace.
func (mr *MockCloudspaceAPIMockRecorder) CreateCloudspace(ctx, cs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCloudspace", reflect.TypeOf((*MockCloudspaceAPI)(nil).CreateCloudspace), ctx, cs)
}

// DeleteCloudspace mocks base method.
func (m *MockCloudspaceAPI) DeleteCloudspace(ctx context.Context, org, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCloudspace", ctx, org, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCloudspace indicates an expected call of DeleteCloudspace.
func (mr *MockCloudspaceAPIMockRecorder) DeleteCloudspace(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCloudspace", reflect.TypeOf((*MockCloudspaceAPI)(nil).DeleteCloudspace), ctx, org, name)
}

// GetCloudspace mocks base method.
func (m *MockCloudspaceAPI) GetCloudspace(ctx context.Context, org, name string) (*rxtspot.CloudSpace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCloudspace", ctx, org, name)
	ret0, _ := ret[0].(*rxtspot.CloudSpace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCloudspace indicates an expected call of GetCloudspace.
func (mr *MockCloudspaceAPIMockRecorder) GetCloudspace(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCloudspace", reflect.TypeOf((*MockCloudspaceAPI)(nil).GetCloudspace), ctx, org, name)
}

// GetCloudspaceConfig mocks base method.
func (m *MockCloudspaceAPI) GetCloudspaceConfig(ctx context.Context, org, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCloudspaceConfig", ctx, org, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCloudspaceConfig indicates an expected call of GetCloudspaceConfig.
func (mr *MockCloudspaceAPIMockRecorder) GetCloudspaceConfig(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCloudspaceConfig", reflect.TypeOf((*MockCloudspaceAPI)(nil).GetCloudspaceConfig), ctx, org, name)
}

// ListCloudspaces mocks base method.
func (m *MockCloudspaceAPI) ListCloudspaces(ctx context.Context, org string) (*rxtspot.CloudSpaceList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCloudspaces", ctx, org)
	ret0, _ := ret[0].(*rxtspot.CloudSpaceList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCloudspaces indicates an expected call of ListCloudspaces.
func (mr *MockCloudspaceAPIMockRecorder) ListCloudspaces(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCloudspaces", reflect.TypeOf((*MockCloudspaceAPI)(nil).ListCloudspaces), ctx, org)
}

// MockSpotNodePoolAPI is a mock of SpotNodePoolAPI interface.
type MockSpotNodePoolAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSpotNodePoolAPIMockRecorder
	isgomock struct{}
}

// MockSpotNodePoolAPIMockRecorder is the mock recorder for MockSpotNodePoolAPI.
type MockSpotNodePoolAPIMockRecorder struct {
	mock *MockSpotNodePoolAPI
}

// NewMockSpotNodePoolAPI creates a new mock instance.
func NewMockSpotNodePoolAPI(ctrl *gomock.Controller) *MockSpotNodePoolAPI {
	mock := &MockSpotNodePoolAPI{ctrl: ctrl}
	mock.recorder = &MockSpotNodePoolAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotNodePoolAPI) EXPECT() *MockSpotNodePoolAPIMockRecorder {
	return m.recorder
}

// CreateSpotNodePool mocks base method.
func (m *MockSpotNodePoolAPI) CreateSpotNodePool(ctx context.Context, org string, pool rxtspot.SpotNodePool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSpotNodePool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSpotNodePool indicates an expected call of CreateSpotNodePool.
func (mr *MockSpotNodePoolAPIMockRecorder) CreateSpotNodePool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSpotNodePool", reflect.TypeOf((*MockSpotNodePoolAPI)(nil).CreateSpotNodePool), ctx, org, pool)
}

// DeleteSpotNodePool mocks base method.
func (m *MockSpotNodePoolAPI) DeleteSpotNodePool(ctx context.Context, org, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSpotNodePool", ctx, org, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSpotNodePool indicates an expected call of DeleteSpotNodePool.
func (mr *MockSpotNodePoolAPIMockRecorder) DeleteSpotNodePool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSpotNodePool", reflect.TypeOf((*MockSpotNodePoolAPI)(nil).DeleteSpotNodePool), ctx, org, name)
}

// GetSpotNodePool mocks base method.
func (m *MockSpotNodePoolAPI) GetSpotNodePool(ctx context.Context, org, name string) (*rxtspot.SpotNodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpotNodePool", ctx, org, name)
	ret0, _ := ret[0].(*rxtspot.SpotNodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpotNodePool indicates an expected call of GetSpotNodePool.
func (mr *MockSpotNodePoolAPIMockRecorder) GetSpotNodePool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpotNodePool", reflect.TypeOf((*MockSpotNodePoolAPI)(nil).GetSpotNodePool), ctx, org, name)
}

// ListSpotNodePools mocks base method.
func (m *MockSpotNodePoolAPI) ListSpotNodePools(ctx context.Context, org, cloudspace string) ([]*rxtspot.SpotNodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSpotNodePools", ctx, org, cloudspace)
	ret0, _ := ret[0].([]*rxtspot.SpotNodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSpotNodePools indicates an expected call of ListSpotNodePools.
func (mr *MockSpotNodePoolAPIMockRecorder) ListSpotNodePools(ctx, org, cloudspace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSpotNodePools", reflect.TypeOf((*MockSpotNodePoolAPI)(nil).ListSpotNodePools), ctx, org, cloudspace)
}

// UpdateSpotNodePool mocks base method.
func (m *MockSpotNodePoolAPI) UpdateSpotNodePool(ctx context.Context, org string, pool rxtspot.SpotNodePool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSpotNodePool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSpotNodePool indicates an expected call of UpdateSpotNodePool.
func (mr *MockSpotNodePoolAPIMockRecorder) UpdateSpotNodePool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSpotNodePool", reflect.TypeOf((*MockSpotNodePoolAPI)(nil).UpdateSpotNodePool), ctx, org, pool)
}

// MockAutopilotNodePoolAPI is a mock of AutopilotNodePoolAPI interface.
type MockAutopilotNodePoolAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAutopilotNodePoolAPIMockRecorder
	isgomock struct{}
}

// MockAutopilotNodePoolAPIMockRecorder is the mock recorder for MockAutopilotNodePoolAPI.
type MockAutopilotNodePoolAPIMockRecorder struct {
	mock *MockAutopilotNodePoolAPI
}

// NewMockAutopilotNodePoolAPI creates a new mock instance.
func NewMockAutopilotNodePoolAPI(ctrl *gomock.Controller) *MockAutopilotNodePoolAPI {
	mock := &MockAutopilotNodePoolAPI{ctrl: ctrl}
	mock.recorder = &MockAutopilotNodePoolAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAutopilotNodePoolAPI) EXPECT() *MockAutopilotNodePoolAPIMockRecorder {
	return m.recorder
}

// CreateAutopilotNodePool mocks base method.
func (m *MockAutopilotNodePoolAPI) CreateAutopilotNodePool(ctx context.Context, org string, pool rxtspot.AutopilotNodePool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAutopilotNodePool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAutopilotNodePool indicates an expected call of CreateAutopilotNodePool.
func (mr *MockAutopilotNodePoolAPIMockRecorder) CreateAutopilotNodePool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAutopilotNodePool", reflect.TypeOf((*MockAutopilotNodePoolAPI)(nil).CreateAutopilotNodePool), ctx, org, pool)
}

// DeleteAutopilotNodePool mocks base method.
func (m *MockAutopilotNodePoolAPI) DeleteAutopilotNodePool(ctx context.Context, org, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAutopilotNodePool", ctx, org, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAutopilotNodePool indicates an expected call of DeleteAutopilotNodePool.
func (mr *MockAutopilotNodePoolAPIMockRecorder) DeleteAutopilotNodePool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAutopilotNodePool", reflect.TypeOf((*MockAutopilotNodePoolAPI)(nil).DeleteAutopilotNodePool), ctx, org, name)
}

// GetAutopilotNodePool mocks base method.
func (m *MockAutopilotNodePoolAPI) GetAutopilotNodePool(ctx context.Context, org, name string) (*rxtspot.AutopilotNodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAutopilotNodePool", ctx, org, name)
	ret0, _ := ret[0].(*rxtspot.AutopilotNodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAutopilotNodePool indicates an expected call of GetAutopilotNodePool.
func (mr *MockAutopilotNodePoolAPIMockRecorder) GetAutopilotNodePool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAutopilotNodePool", reflect.TypeOf((*MockAutopilotNodePoolAPI)(nil).GetAutopilotNodePool), ctx, org, name)
}

// ListAutopilotNodePools mocks base method.
func (m *MockAutopilotNodePoolAPI) ListAutopilotNodePools(ctx context.Context, org, cloudspace string) ([]*rxtspot.AutopilotNodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAutopilotNodePools", ctx, org, cloudspace)
	ret0, _ := ret[0].([]*rxtspot.AutopilotNodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAutopilotNodePools indicates an expected call of ListAutopilotNodePools.
func (mr *MockAutopilotNodePoolAPIMockRecorder) ListAutopilotNodePools(ctx, org, cloudspace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAutopilotNodePools", reflect.TypeOf((*MockAutopilotNodePoolAPI)(nil).ListAutopilotNodePools), ctx, org, cloudspace)
}

// UpdateAutopilotNodePool mocks base method.
func (m *MockAutopilotNodePoolAPI) UpdateAutopilotNodePool(ctx context.Context, org string, pool rxtspot.AutopilotNodePool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAutopilotNodePool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAutopilotNodePool indicates an expected call of UpdateAutopilotNodePool.
func (mr *MockAutopilotNodePoolAPIMockRecorder) UpdateAutopilotNodePool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAutopilotNodePool", reflect.TypeOf((*MockAutopilotNodePoolAPI)(nil).UpdateAutopilotNodePool), ctx, org, pool)
}

// MockOnDemandNodePoolAPI is a mock of OnDemandNodePoolAPI interface.
type MockOnDemandNodePoolAPI struct {
	ctrl     *gomock.Controller
	recorder *MockOnDemandNodePoolAPIMockRecorder
	isgomock struct{}
}

// MockOnDemandNodePoolAPIMockRecorder is the mock recorder for MockOnDemandNodePoolAPI.
type MockOnDemandNodePoolAPIMockRecorder struct {
	mock *MockOnDemandNodePoolAPI
}

// NewMockOnDemandNodePoolAPI creates a new mock instance.
func NewMockOnDemandNodePoolAPI(ctrl *gomock.Controller) *MockOnDemandNodePoolAPI {
	mock := &MockOnDemandNodePoolAPI{ctrl: ctrl}
	mock.recorder = &MockOnDemandNodePoolAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOnDemandNodePoolAPI) EXPECT() *MockOnDemandNodePoolAPIMockRecorder {
	return m.recorder
}

// CreateOnDemandNodePool mocks base method.
func (m *MockOnDemandNodePoolAPI) CreateOnDemandNodePool(ctx context.Context, org string, pool rxtspot.OnDemandNodePool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOnDemandNodePool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOnDemandNodePool indicates an expected call of CreateOnDemandNodePool.
func (mr *MockOnDemandNodePoolAPIMockRecorder) CreateOnDemandNodePool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOnDemandNodePool", reflect.TypeOf((*MockOnDemandNodePoolAPI)(nil).CreateOnDemandNodePool), ctx, org, pool)
}

// DeleteOnDemandNodePool mocks base method.
func (m *MockOnDemandNodePoolAPI) DeleteOnDemandNodePool(ctx context.Context, org, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOnDemandNodePool", ctx, org, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOnDemandNodePool indicates an expected call of DeleteOnDemandNodePool.
func (mr *MockOnDemandNodePoolAPIMockRecorder) DeleteOnDemandNodePool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOnDemandNodePool", reflect.TypeOf((*MockOnDemandNodePoolAPI)(nil).DeleteOnDemandNodePool), ctx, org, name)
}

// GetOnDemandNodePool mocks base method.
func (m *MockOnDemandNodePoolAPI) GetOnDemandNodePool(ctx context.Context, org, name string) (*rxtspot.OnDemandNodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOnDemandNodePool", ctx, org, name)
	ret0, _ := ret[0].(*rxtspot.OnDemandNodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOnDemandNodePool indicates an expected call of GetOnDemandNodePool.
func (mr *MockOnDemandNodePoolAPIMockRecorder) GetOnDemandNodePool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOnDemandNodePool", reflect.TypeOf((*MockOnDemandNodePoolAPI)(nil).GetOnDemandNodePool), ctx, org, name)
}

// ListOnDemandNodePools mocks base method.
func (m *MockOnDemandNodePoolAPI) ListOnDemandNodePools(ctx context.Context, org, cloudspace string) ([]*rxtspot.OnDemandNodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOnDemandNodePools", ctx, org, cloudspace)
	ret0, _ := ret[0].([]*rxtspot.OnDemandNodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOnDemandNodePools indicates an expected call of ListOnDemandNodePools.
func (mr *MockOnDemandNodePoolAPIMockRecorder) ListOnDemandNodePools(ctx, org, cloudspace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOnDemandNodePools", reflect.TypeOf((*MockOnDemandNodePoolAPI)(nil).ListOnDemandNodePools), ctx, org, cloudspace)
}

// UpdateOnDemandNodePool mocks base method.
func (m *MockOnDemandNodePoolAPI) UpdateOnDemandNodePool(ctx context.Context, org string, pool rxtspot.OnDemandNodePool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOnDemandNodePool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOnDemandNodePool indicates an expected call of UpdateOnDemandNodePool.
func (mr *MockOnDemandNodePoolAPIMockRecorder) UpdateOnDemandNodePool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOnDemandNodePool", reflect.TypeOf((*MockOnDemandNodePoolAPI)(nil).UpdateOnDemandNodePool), ctx, org, pool)
}

// MockSpotRegionsAPI is a mock of SpotRegionsAPI interface.
type MockSpotRegionsAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSpotRegionsAPIMockRecorder
	isgomock struct{}
}

// MockSpotRegionsAPIMockRecorder is the mock recorder for MockSpotRegionsAPI.
type MockSpotRegionsAPIMockRecorder struct {
	mock *MockSpotRegionsAPI
}

// NewMockSpotRegionsAPI creates a new mock instance.
func NewMockSpotRegionsAPI(ctrl *gomock.Controller) *MockSpotRegionsAPI {
	mock := &MockSpotRegionsAPI{ctrl: ctrl}
	mock.recorder = &MockSpotRegionsAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotRegionsAPI) EXPECT() *MockSpotRegionsAPIMockRecorder {
	return m.recorder
}

// GetRegion mocks base method.
func (m *MockSpotRegionsAPI) GetRegion(ctx context.Context, name string) (*rxtspot.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegion", ctx, name)
	ret0, _ := ret[0].(*rxtspot.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegion indicates an expected call of GetRegion.
func (mr *MockSpotRegionsAPIMockRecorder) GetRegion(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegion", reflect.TypeOf((*MockSpotRegionsAPI)(nil).GetRegion), ctx, name)
}

// ListRegions mocks base method.
func (m *MockSpotRegionsAPI) ListRegions(ctx context.Context) ([]rxtspot.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRegions", ctx)
	ret0, _ := ret[0].([]rxtspot.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRegions indicates an expected call of ListRegions.
func (mr *MockSpotRegionsAPIMockRecorder) ListRegions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRegions", reflect.TypeOf((*MockSpotRegionsAPI)(nil).ListRegions), ctx)
}

// MockSpotServerClassesAPI is a mock of SpotServerClassesAPI interface.
type MockSpotServerClassesAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSpotServerClassesAPIMockRecorder
	isgomock struct{}
}

// MockSpotServerClassesAPIMockRecorder is the mock recorder for MockSpotServerClassesAPI.
type MockSpotServerClassesAPIMockRecorder struct {
	mock *MockSpotServerClassesAPI
}

// NewMockSpotServerClassesAPI creates a new mock instance.
func NewMockSpotServerClassesAPI(ctrl *gomock.Controller) *MockSpotServerClassesAPI {
	mock := &MockSpotServerClassesAPI{ctrl: ctrl}
	mock.recorder = &MockSpotServerClassesAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotServerClassesAPI) EXPECT() *MockSpotServerClassesAPIMockRecorder {
	return m.recorder
}

// GetServerClass mocks base method.
func (m *MockSpotServerClassesAPI) GetServerClass(ctx context.Context, name string) (*rxtspot.ServerClass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerClass", ctx, name)
	ret0, _ := ret[0].(*rxtspot.ServerClass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerClass indicates an expected call of GetServerClass.
func (mr *MockSpotServerClassesAPIMockRecorder) GetServerClass(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerClass", reflect.TypeOf((*MockSpotServerClassesAPI)(nil).GetServerClass), ctx, name)
}

// ListServerClasses mocks base method.
func (m *MockSpotServerClassesAPI) ListServerClasses(ctx context.Context, region string) (*rxtspot.ServerClassList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServerClasses", ctx, region)
	ret0, _ := ret[0].(*rxtspot.ServerClassList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServerClasses indicates an expected call of ListServerClasses.
func (mr *MockSpotServerClassesAPIMockRecorder) ListServerClasses(ctx, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServerClasses", reflect.TypeOf((*MockSpotServerClassesAPI)(nil).ListServerClasses), ctx, region)
}

// MockSpotPricingAPI is a mock of SpotPricingAPI interface.
type MockSpotPricingAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSpotPricingAPIMockRecorder
	isgomock struct{}
}

// MockSpotPricingAPIMockRecorder is the mock recorder for MockSpotPricingAPI.
type MockSpotPricingAPIMockRecorder struct {
	mock *MockSpotPricingAPI
}

// NewMockSpotPricingAPI creates a new mock instance.
func NewMockSpotPricingAPI(ctrl *gomock.Controller) *MockSpotPricingAPI {
	mock := &MockSpotPricingAPI{ctrl: ctrl}
	mock.recorder = &MockSpotPricingAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotPricingAPI) EXPECT() *MockSpotPricingAPIMockRecorder {
	return m.recorder
}

// GetMarketPriceForServerClass mocks base method.
func (m *MockSpotPricingAPI) GetMarketPriceForServerClass(ctx context.Context, serverClassStatus *rxtspot.ServerClassStatus) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMarketPriceForServerClass", ctx, serverClassStatus)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetMarketPriceForServerClass indicates an expected call of GetMarketPriceForServerClass.
func (mr *MockSpotPricingAPIMockRecorder) GetMarketPriceForServerClass(ctx, serverClassStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMarketPriceForServerClass", reflect.TypeOf((*MockSpotPricingAPI)(nil).GetMarketPriceForServerClass), ctx, serverClassStatus)
}

// GetMinimumBidPriceForServerClass mocks base method.
func (m *MockSpotPricingAPI) GetMinimumBidPriceForServerClass(ctx context.Context, serverClassSpec *rxtspot.ServerClassSpec) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinimumBidPriceForServerClass", ctx, serverClassSpec)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetMinimumBidPriceForServerClass indicates an expected call of GetMinimumBidPriceForServerClass.
func (mr *MockSpotPricingAPIMockRecorder) GetMinimumBidPriceForServerClass(ctx, serverClassSpec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinimumBidPriceForServerClass", reflect.TypeOf((*MockSpotPricingAPI)(nil).GetMinimumBidPriceForServerClass), ctx, serverClassSpec)
}

// GetPriceDetails mocks base method.
func (m *MockSpotPricingAPI) GetPriceDetails(ctx context.Context) ([]*rxtspot.PriceDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceDetails", ctx)
	ret0, _ := ret[0].([]*rxtspot.PriceDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceDetails indicates an expected call of GetPriceDetails.
func (mr *MockSpotPricingAPIMockRecorder) GetPriceDetails(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceDetails", reflect.TypeOf((*MockSpotPricingAPI)(nil).GetPriceDetails), ctx)
}

// GetPriceDetailsForRegion mocks base method.
func (m *MockSpotPricingAPI) GetPriceDetailsForRegion(ctx context.Context, region string) (*rxtspot.PriceDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceDetailsForRegion", ctx, region)
	ret0, _ := ret[0].(*rxtspot.PriceDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceDetailsForRegion indicates an expected call of GetPriceDetailsForRegion.
func (mr *MockSpotPricingAPIMockRecorder) GetPriceDetailsForRegion(ctx, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceDetailsForRegion", reflect.TypeOf((*MockSpotPricingAPI)(nil).GetPriceDetailsForRegion), ctx, region)
}

// GetPriceDetailsForServerClass mocks base method.
func (m *MockSpotPricingAPI) GetPriceDetailsForServerClass(ctx context.Context, serverClass string) (*rxtspot.PriceDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceDetailsForServerClass", ctx, serverClass)
	ret0, _ := ret[0].(*rxtspot.PriceDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceDetailsForServerClass indicates an expected call of GetPriceDetailsForServerClass.
func (mr *MockSpotPricingAPIMockRecorder) GetPriceDetailsForServerClass(ctx, serverClass any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceDetailsForServerClass", reflect.TypeOf((*MockSpotPricingAPI)(nil).GetPriceDetailsForServerClass), ctx, serverClass)
}

// MockVMCloudSpaceAPI is a mock of VMCloudSpaceAPI interface.
type MockVMCloudSpaceAPI struct {
	ctrl     *gomock.Controller
	recorder *MockVMCloudSpaceAPIMockRecorder
	isgomock struct{}
}

// MockVMCloudSpaceAPIMockRecorder is the mock recorder for MockVMCloudSpaceAPI.
type MockVMCloudSpaceAPIMockRecorder struct {
	mock *MockVMCloudSpaceAPI
}

// NewMockVMCloudSpaceAPI creates a new mock instance.
func NewMockVMCloudSpaceAPI(ctrl *gomock.Controller) *MockVMCloudSpaceAPI {
	mock := &MockVMCloudSpaceAPI{ctrl: ctrl}
	mock.recorder = &MockVMCloudSpaceAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVMCloudSpaceAPI) EXPECT() *MockVMCloudSpaceAPIMockRecorder {
	return m.recorder
}

// CreateVMCloudSpace mocks base method.
func (m *MockVMCloudSpaceAPI) CreateVMCloudSpace(ctx context.Context, vmcs rxtspot.VMCloudSpace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVMCloudSpace", ctx, vmcs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVMCloudSpace indicates an expected call of CreateVMCloudSpace.
func (mr *MockVMCloudSpaceAPIMockRecorder) CreateVMCloudSpace(ctx, vmcs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVMCloudSpace", reflect.TypeOf((*MockVMCloudSpaceAPI)(nil).CreateVMCloudSpace), ctx, vmcs)
}

// DeleteVMCloudSpace mocks base method.
func (m *MockVMCloudSpaceAPI) DeleteVMCloudSpace(ctx context.Context, org, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVMCloudSpace", ctx, org, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVMCloudSpace indicates an expected call of DeleteVMCloudSpace.
func (mr *MockVMCloudSpaceAPIMockRecorder) DeleteVMCloudSpace(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVMCloudSpace", reflect.TypeOf((*MockVMCloudSpaceAPI)(nil).DeleteVMCloudSpace), ctx, org, name)
}

// GetVMCloudSpace mocks base method.
func (m *MockVMCloudSpaceAPI) GetVMCloudSpace(ctx context.Context, org, name string) (*rxtspot.VMCloudSpace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVMCloudSpace", ctx, org, name)
	ret0, _ := ret[0].(*rxtspot.VMCloudSpace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVMCloudSpace indicates an expected call of GetVMCloudSpace.
func (mr *MockVMCloudSpaceAPIMockRecorder) GetVMCloudSpace(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVMCloudSpace", reflect.TypeOf((*MockVMCloudSpaceAPI)(nil).GetVMCloudSpace), ctx, org, name)
}

// ListVMCloudSpaces mocks base method.
func (m *MockVMCloudSpaceAPI) ListVMCloudSpaces(ctx context.Context, org string) (*rxtspot.VMCloudSpaceList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVMCloudSpaces", ctx, org)
	ret0, _ := ret[0].(*rxtspot.VMCloudSpaceList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVMCloudSpaces indicates an expected call of ListVMCloudSpaces.
func (mr *MockVMCloudSpaceAPIMockRecorder) ListVMCloudSpaces(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVMCloudSpaces", reflect.TypeOf((*MockVMCloudSpaceAPI)(nil).ListVMCloudSpaces), ctx, org)
}

// UpdateVMCloudSpace mocks base method.
func (m *MockVMCloudSpaceAPI) UpdateVMCloudSpace(ctx context.Context, org string, vmcs rxtspot.VMCloudSpace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVMCloudSpace", ctx, org, vmcs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVMCloudSpace indicates an expected call of UpdateVMCloudSpace.
func (mr *MockVMCloudSpaceAPIMockRecorder) UpdateVMCloudSpace(ctx, org, vmcs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVMCloudSpace", reflect.TypeOf((*MockVMCloudSpaceAPI)(nil).UpdateVMCloudSpace), ctx, org, vmcs)
}

// MockVMPoolAPI is a mock of VMPoolAPI interface.
type MockVMPoolAPI struct {
	ctrl     *gomock.Controller
	recorder *MockVMPoolAPIMockRecorder
	isgomock struct{}
}

// MockVMPoolAPIMockRecorder is the mock recorder for MockVMPoolAPI.
type MockVMPoolAPIMockRecorder struct {
	mock *MockVMPoolAPI
}

// NewMockVMPoolAPI creates a new mock instance.
func NewMockVMPoolAPI(ctrl *gomock.Controller) *MockVMPoolAPI {
	mock := &MockVMPoolAPI{ctrl: ctrl}
	mock.recorder = &MockVMPoolAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVMPoolAPI) EXPECT() *MockVMPoolAPIMockRecorder {
	return m.recorder
}

// CreateVMPool mocks base method.
func (m *MockVMPoolAPI) CreateVMPool(ctx context.Context, org string, pool rxtspot.VMPool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVMPool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVMPool indicates an expected call of CreateVMPool.
func (mr *MockVMPoolAPIMockRecorder) CreateVMPool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVMPool", reflect.TypeOf((*MockVMPoolAPI)(nil).CreateVMPool), ctx, org, pool)
}

// DeleteVMPool mocks base method.
func (m *MockVMPoolAPI) DeleteVMPool(ctx context.Context, org, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVMPool", ctx, org, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVMPool indicates an expected call of DeleteVMPool.
func (mr *MockVMPoolAPIMockRecorder) DeleteVMPool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVMPool", reflect.TypeOf((*MockVMPoolAPI)(nil).DeleteVMPool), ctx, org, name)
}

// GetVMPool mocks base method.
func (m *MockVMPoolAPI) GetVMPool(ctx context.Context, org, name string) (*rxtspot.VMPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVMPool", ctx, org, name)
	ret0, _ := ret[0].(*rxtspot.VMPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVMPool indicates an expected call of GetVMPool.
func (mr *MockVMPoolAPIMockRecorder) GetVMPool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVMPool", reflect.TypeOf((*MockVMPoolAPI)(nil).GetVMPool), ctx, org, name)
}

// ListVMPools mocks base method.
func (m *MockVMPoolAPI) ListVMPools(ctx context.Context, org, vmCloudSpace string) ([]*rxtspot.VMPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVMPools", ctx, org, vmCloudSpace)
	ret0, _ := ret[0].([]*rxtspot.VMPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVMPools indicates an expected call of ListVMPools.
func (mr *MockVMPoolAPIMockRecorder) ListVMPools(ctx, org, vmCloudSpace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVMPools", reflect.TypeOf((*MockVMPoolAPI)(nil).ListVMPools), ctx, org, vmCloudSpace)
}

// UpdateVMPool mocks base method.
func (m *MockVMPoolAPI) UpdateVMPool(ctx context.Context, org string, pool rxtspot.VMPool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVMPool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVMPool indicates an expected call of UpdateVMPool.
func (mr *MockVMPoolAPIMockRecorder) UpdateVMPool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVMPool", reflect.TypeOf((*MockVMPoolAPI)(nil).UpdateVMPool), ctx, org, pool)
}

// MockVMSSHKeyAPI is a mock of VMSSHKeyAPI interface.
type MockVMSSHKeyAPI struct {
	ctrl     *gomock.Controller
	recorder *MockVMSSHKeyAPIMockRecorder
	isgomock struct{}
}

// MockVMSSHKeyAPIMockRecorder is the mock recorder for MockVMSSHKeyAPI.
type MockVMSSHKeyAPIMockRecorder struct {
	mock *MockVMSSHKeyAPI
}

// NewMockVMSSHKeyAPI creates a new mock instance.
func NewMockVMSSHKeyAPI(ctrl *gomock.Controller) *MockVMSSHKeyAPI {
	mock := &MockVMSSHKeyAPI{ctrl: ctrl}
	mock.recorder = &MockVMSSHKeyAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVMSSHKeyAPI) EXPECT() *MockVMSSHKeyAPIMockRecorder {
	return m.recorder
}

// CreateVMSSHKey mocks base method.
func (m *MockVMSSHKeyAPI) CreateVMSSHKey(ctx context.Context, key rxtspot.VMSSHKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVMSSHKey", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVMSSHKey indicates an expected call of CreateVMSSHKey.
func (mr *MockVMSSHKeyAPIMockRecorder) CreateVMSSHKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVMSSHKey", reflect.TypeOf((*MockVMSSHKeyAPI)(nil).CreateVMSSHKey), ctx, key)
}

// DeleteVMSSHKey mocks base method.
func (m *MockVMSSHKeyAPI) DeleteVMSSHKey(ctx context.Context, org, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVMSSHKey", ctx, org, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVMSSHKey indicates an expected call of DeleteVMSSHKey.
func (mr *MockVMSSHKeyAPIMockRecorder) DeleteVMSSHKey(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVMSSHKey", reflect.TypeOf((*MockVMSSHKeyAPI)(nil).DeleteVMSSHKey), ctx, org, name)
}

// GetVMSSHKey mocks base method.
func (m *MockVMSSHKeyAPI) GetVMSSHKey(ctx context.Context, org, name string) (*rxtspot.VMSSHKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVMSSHKey", ctx, org, name)
	ret0, _ := ret[0].(*rxtspot.VMSSHKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVMSSHKey indicates an expected call of GetVMSSHKey.
func (mr *MockVMSSHKeyAPIMockRecorder) GetVMSSHKey(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVMSSHKey", reflect.TypeOf((*MockVMSSHKeyAPI)(nil).GetVMSSHKey), ctx, org, name)
}

// ListVMSSHKeys mocks base method.
func (m *MockVMSSHKeyAPI) ListVMSSHKeys(ctx context.Context, org string) (*rxtspot.VMSSHKeyList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVMSSHKeys", ctx, org)
	ret0, _ := ret[0].(*rxtspot.VMSSHKeyList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVMSSHKeys indicates an expected call of ListVMSSHKeys.
func (mr *MockVMSSHKeyAPIMockRecorder) ListVMSSHKeys(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVMSSHKeys", reflect.TypeOf((*MockVMSSHKeyAPI)(nil).ListVMSSHKeys), ctx, org)
}

// MockSpotAPI is a mock of SpotAPI interface.
type MockSpotAPI struct {
	ctrl     *gomock.Controller
	recorder *MockSpotAPIMockRecorder
	isgomock struct{}
}

// MockSpotAPIMockRecorder is the mock recorder for MockSpotAPI.
type MockSpotAPIMockRecorder struct {
	mock *MockSpotAPI
}

// NewMockSpotAPI creates a new mock instance.
func NewMockSpotAPI(ctrl *gomock.Controller) *MockSpotAPI {
	mock := &MockSpotAPI{ctrl: ctrl}
	mock.recorder = &MockSpotAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpotAPI) EXPECT() *MockSpotAPIMockRecorder {
	return m.recorder
}

// Authenticate mocks base method.
func (m *MockSpotAPI) Authenticate(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockSpotAPIMockRecorder) Authenticate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockSpotAPI)(nil).Authenticate), ctx)
}

// CreateAutopilotNodePool mocks base method.
func (m *MockSpotAPI) CreateAutopilotNodePool(ctx context.Context, org string, pool rxtspot.AutopilotNodePool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAutopilotNodePool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAutopilotNodePool indicates an expected call of CreateAutopilotNodePool.
func (mr *MockSpotAPIMockRecorder) CreateAutopilotNodePool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAutopilotNodePool", reflect.TypeOf((*MockSpotAPI)(nil).CreateAutopilotNodePool), ctx, org, pool)
}

// CreateCloudspace mocks base method.
func (m *MockSpotAPI) CreateCloudspace(ctx context.Context, cs rxtspot.CloudSpace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCloudspace", ctx, cs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCloudspace indicates an expected call of CreateCloudspace.
func (mr *MockSpotAPIMockRecorder) CreateCloudspace(ctx, cs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCloudspace", reflect.TypeOf((*MockSpotAPI)(nil).CreateCloudspace), ctx, cs)
}

// CreateOnDemandNodePool mocks base method.
func (m *MockSpotAPI) CreateOnDemandNodePool(ctx context.Context, org string, pool rxtspot.OnDemandNodePool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOnDemandNodePool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOnDemandNodePool indicates an expected call of CreateOnDemandNodePool.
func (mr *MockSpotAPIMockRecorder) CreateOnDemandNodePool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOnDemandNodePool", reflect.TypeOf((*MockSpotAPI)(nil).CreateOnDemandNodePool), ctx, org, pool)
}

// CreateSpotNodePool mocks base method.
func (m *MockSpotAPI) CreateSpotNodePool(ctx context.Context, org string, pool rxtspot.SpotNodePool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSpotNodePool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSpotNodePool indicates an expected call of CreateSpotNodePool.
func (mr *MockSpotAPIMockRecorder) CreateSpotNodePool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSpotNodePool", reflect.TypeOf((*MockSpotAPI)(nil).CreateSpotNodePool), ctx, org, pool)
}

// CreateVMCloudSpace mocks base method.
func (m *MockSpotAPI) CreateVMCloudSpace(ctx context.Context, vmcs rxtspot.VMCloudSpace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVMCloudSpace", ctx, vmcs)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVMCloudSpace indicates an expected call of CreateVMCloudSpace.
func (mr *MockSpotAPIMockRecorder) CreateVMCloudSpace(ctx, vmcs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVMCloudSpace", reflect.TypeOf((*MockSpotAPI)(nil).CreateVMCloudSpace), ctx, vmcs)
}

// CreateVMPool mocks base method.
func (m *MockSpotAPI) CreateVMPool(ctx context.Context, org string, pool rxtspot.VMPool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVMPool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVMPool indicates an expected call of CreateVMPool.
func (mr *MockSpotAPIMockRecorder) CreateVMPool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVMPool", reflect.TypeOf((*MockSpotAPI)(nil).CreateVMPool), ctx, org, pool)
}

// CreateVMSSHKey mocks base method.
func (m *MockSpotAPI) CreateVMSSHKey(ctx context.Context, key rxtspot.VMSSHKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVMSSHKey", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVMSSHKey indicates an expected call of CreateVMSSHKey.
func (mr *MockSpotAPIMockRecorder) CreateVMSSHKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVMSSHKey", reflect.TypeOf((*MockSpotAPI)(nil).CreateVMSSHKey), ctx, key)
}

// DeleteAutopilotNodePool mocks base method.
func (m *MockSpotAPI) DeleteAutopilotNodePool(ctx context.Context, org, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAutopilotNodePool", ctx, org, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAutopilotNodePool indicates an expected call of DeleteAutopilotNodePool.
func (mr *MockSpotAPIMockRecorder) DeleteAutopilotNodePool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAutopilotNodePool", reflect.TypeOf((*MockSpotAPI)(nil).DeleteAutopilotNodePool), ctx, org, name)
}

// DeleteCloudspace mocks base method.
func (m *MockSpotAPI) DeleteCloudspace(ctx context.Context, org, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCloudspace", ctx, org, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCloudspace indicates an expected call of DeleteCloudspace.
func (mr *MockSpotAPIMockRecorder) DeleteCloudspace(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCloudspace", reflect.TypeOf((*MockSpotAPI)(nil).DeleteCloudspace), ctx, org, name)
}

// DeleteOnDemandNodePool mocks base method.
func (m *MockSpotAPI) DeleteOnDemandNodePool(ctx context.Context, org, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOnDemandNodePool", ctx, org, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOnDemandNodePool indicates an expected call of DeleteOnDemandNodePool.
func (mr *MockSpotAPIMockRecorder) DeleteOnDemandNodePool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOnDemandNodePool", reflect.TypeOf((*MockSpotAPI)(nil).DeleteOnDemandNodePool), ctx, org, name)
}

// DeleteSpotNodePool mocks base method.
func (m *MockSpotAPI) DeleteSpotNodePool(ctx context.Context, org, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSpotNodePool", ctx, org, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSpotNodePool indicates an expected call of DeleteSpotNodePool.
func (mr *MockSpotAPIMockRecorder) DeleteSpotNodePool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSpotNodePool", reflect.TypeOf((*MockSpotAPI)(nil).DeleteSpotNodePool), ctx, org, name)
}

// DeleteVMCloudSpace mocks base method.
func (m *MockSpotAPI) DeleteVMCloudSpace(ctx context.Context, org, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVMCloudSpace", ctx, org, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVMCloudSpace indicates an expected call of DeleteVMCloudSpace.
func (mr *MockSpotAPIMockRecorder) DeleteVMCloudSpace(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVMCloudSpace", reflect.TypeOf((*MockSpotAPI)(nil).DeleteVMCloudSpace), ctx, org, name)
}

// DeleteVMPool mocks base method.
func (m *MockSpotAPI) DeleteVMPool(ctx context.Context, org, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVMPool", ctx, org, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVMPool indicates an expected call of DeleteVMPool.
func (mr *MockSpotAPIMockRecorder) DeleteVMPool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVMPool", reflect.TypeOf((*MockSpotAPI)(nil).DeleteVMPool), ctx, org, name)
}

// DeleteVMSSHKey mocks base method.
func (m *MockSpotAPI) DeleteVMSSHKey(ctx context.Context, org, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVMSSHKey", ctx, org, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVMSSHKey indicates an expected call of DeleteVMSSHKey.
func (mr *MockSpotAPIMockRecorder) DeleteVMSSHKey(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVMSSHKey", reflect.TypeOf((*MockSpotAPI)(nil).DeleteVMSSHKey), ctx, org, name)
}

// GetAutopilotNodePool mocks base method.
func (m *MockSpotAPI) GetAutopilotNodePool(ctx context.Context, org, name string) (*rxtspot.AutopilotNodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAutopilotNodePool", ctx, org, name)
	ret0, _ := ret[0].(*rxtspot.AutopilotNodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAutopilotNodePool indicates an expected call of GetAutopilotNodePool.
func (mr *MockSpotAPIMockRecorder) GetAutopilotNodePool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAutopilotNodePool", reflect.TypeOf((*MockSpotAPI)(nil).GetAutopilotNodePool), ctx, org, name)
}

// GetCloudspace mocks base method.
func (m *MockSpotAPI) GetCloudspace(ctx context.Context, org, name string) (*rxtspot.CloudSpace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCloudspace", ctx, org, name)
	ret0, _ := ret[0].(*rxtspot.CloudSpace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCloudspace indicates an expected call of GetCloudspace.
func (mr *MockSpotAPIMockRecorder) GetCloudspace(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCloudspace", reflect.TypeOf((*MockSpotAPI)(nil).GetCloudspace), ctx, org, name)
}

// GetCloudspaceConfig mocks base method.
func (m *MockSpotAPI) GetCloudspaceConfig(ctx context.Context, org, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCloudspaceConfig", ctx, org, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCloudspaceConfig indicates an expected call of GetCloudspaceConfig.
func (mr *MockSpotAPIMockRecorder) GetCloudspaceConfig(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCloudspaceConfig", reflect.TypeOf((*MockSpotAPI)(nil).GetCloudspaceConfig), ctx, org, name)
}

// GetMarketPriceForServerClass mocks base method.
func (m *MockSpotAPI) GetMarketPriceForServerClass(ctx context.Context, serverClassStatus *rxtspot.ServerClassStatus) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMarketPriceForServerClass", ctx, serverClassStatus)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetMarketPriceForServerClass indicates an expected call of GetMarketPriceForServerClass.
func (mr *MockSpotAPIMockRecorder) GetMarketPriceForServerClass(ctx, serverClassStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMarketPriceForServerClass", reflect.TypeOf((*MockSpotAPI)(nil).GetMarketPriceForServerClass), ctx, serverClassStatus)
}

// GetMinimumBidPriceForServerClass mocks base method.
func (m *MockSpotAPI) GetMinimumBidPriceForServerClass(ctx context.Context, serverClassSpec *rxtspot.ServerClassSpec) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMinimumBidPriceForServerClass", ctx, serverClassSpec)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetMinimumBidPriceForServerClass indicates an expected call of GetMinimumBidPriceForServerClass.
func (mr *MockSpotAPIMockRecorder) GetMinimumBidPriceForServerClass(ctx, serverClassSpec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMinimumBidPriceForServerClass", reflect.TypeOf((*MockSpotAPI)(nil).GetMinimumBidPriceForServerClass), ctx, serverClassSpec)
}

// GetOnDemandNodePool mocks base method.
func (m *MockSpotAPI) GetOnDemandNodePool(ctx context.Context, org, name string) (*rxtspot.OnDemandNodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOnDemandNodePool", ctx, org, name)
	ret0, _ := ret[0].(*rxtspot.OnDemandNodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOnDemandNodePool indicates an expected call of GetOnDemandNodePool.
func (mr *MockSpotAPIMockRecorder) GetOnDemandNodePool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOnDemandNodePool", reflect.TypeOf((*MockSpotAPI)(nil).GetOnDemandNodePool), ctx, org, name)
}

// GetPriceDetails mocks base method.
func (m *MockSpotAPI) GetPriceDetails(ctx context.Context) ([]*rxtspot.PriceDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceDetails", ctx)
	ret0, _ := ret[0].([]*rxtspot.PriceDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceDetails indicates an expected call of GetPriceDetails.
func (mr *MockSpotAPIMockRecorder) GetPriceDetails(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceDetails", reflect.TypeOf((*MockSpotAPI)(nil).GetPriceDetails), ctx)
}

// GetPriceDetailsForRegion mocks base method.
func (m *MockSpotAPI) GetPriceDetailsForRegion(ctx context.Context, region string) (*rxtspot.PriceDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceDetailsForRegion", ctx, region)
	ret0, _ := ret[0].(*rxtspot.PriceDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceDetailsForRegion indicates an expected call of GetPriceDetailsForRegion.
func (mr *MockSpotAPIMockRecorder) GetPriceDetailsForRegion(ctx, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceDetailsForRegion", reflect.TypeOf((*MockSpotAPI)(nil).GetPriceDetailsForRegion), ctx, region)
}

// GetPriceDetailsForServerClass mocks base method.
func (m *MockSpotAPI) GetPriceDetailsForServerClass(ctx context.Context, serverClass string) (*rxtspot.PriceDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceDetailsForServerClass", ctx, serverClass)
	ret0, _ := ret[0].(*rxtspot.PriceDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceDetailsForServerClass indicates an expected call of GetPriceDetailsForServerClass.
func (mr *MockSpotAPIMockRecorder) GetPriceDetailsForServerClass(ctx, serverClass any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceDetailsForServerClass", reflect.TypeOf((*MockSpotAPI)(nil).GetPriceDetailsForServerClass), ctx, serverClass)
}

// GetRegion mocks base method.
func (m *MockSpotAPI) GetRegion(ctx context.Context, name string) (*rxtspot.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegion", ctx, name)
	ret0, _ := ret[0].(*rxtspot.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegion indicates an expected call of GetRegion.
func (mr *MockSpotAPIMockRecorder) GetRegion(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegion", reflect.TypeOf((*MockSpotAPI)(nil).GetRegion), ctx, name)
}

// GetServerClass mocks base method.
func (m *MockSpotAPI) GetServerClass(ctx context.Context, name string) (*rxtspot.ServerClass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServerClass", ctx, name)
	ret0, _ := ret[0].(*rxtspot.ServerClass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServerClass indicates an expected call of GetServerClass.
func (mr *MockSpotAPIMockRecorder) GetServerClass(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServerClass", reflect.TypeOf((*MockSpotAPI)(nil).GetServerClass), ctx, name)
}

// GetSpotNodePool mocks base method.
func (m *MockSpotAPI) GetSpotNodePool(ctx context.Context, org, name string) (*rxtspot.SpotNodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpotNodePool", ctx, org, name)
	ret0, _ := ret[0].(*rxtspot.SpotNodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSpotNodePool indicates an expected call of GetSpotNodePool.
func (mr *MockSpotAPIMockRecorder) GetSpotNodePool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpotNodePool", reflect.TypeOf((*MockSpotAPI)(nil).GetSpotNodePool), ctx, org, name)
}

// GetVMCloudSpace mocks base method.
func (m *MockSpotAPI) GetVMCloudSpace(ctx context.Context, org, name string) (*rxtspot.VMCloudSpace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVMCloudSpace", ctx, org, name)
	ret0, _ := ret[0].(*rxtspot.VMCloudSpace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVMCloudSpace indicates an expected call of GetVMCloudSpace.
func (mr *MockSpotAPIMockRecorder) GetVMCloudSpace(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVMCloudSpace", reflect.TypeOf((*MockSpotAPI)(nil).GetVMCloudSpace), ctx, org, name)
}

// GetVMPool mocks base method.
func (m *MockSpotAPI) GetVMPool(ctx context.Context, org, name string) (*rxtspot.VMPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVMPool", ctx, org, name)
	ret0, _ := ret[0].(*rxtspot.VMPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVMPool indicates an expected call of GetVMPool.
func (mr *MockSpotAPIMockRecorder) GetVMPool(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVMPool", reflect.TypeOf((*MockSpotAPI)(nil).GetVMPool), ctx, org, name)
}

// GetVMSSHKey mocks base method.
func (m *MockSpotAPI) GetVMSSHKey(ctx context.Context, org, name string) (*rxtspot.VMSSHKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVMSSHKey", ctx, org, name)
	ret0, _ := ret[0].(*rxtspot.VMSSHKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVMSSHKey indicates an expected call of GetVMSSHKey.
func (mr *MockSpotAPIMockRecorder) GetVMSSHKey(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVMSSHKey", reflect.TypeOf((*MockSpotAPI)(nil).GetVMSSHKey), ctx, org, name)
}

// ListAutopilotNodePools mocks base method.
func (m *MockSpotAPI) ListAutopilotNodePools(ctx context.Context, org, cloudspace string) ([]*rxtspot.AutopilotNodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAutopilotNodePools", ctx, org, cloudspace)
	ret0, _ := ret[0].([]*rxtspot.AutopilotNodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAutopilotNodePools indicates an expected call of ListAutopilotNodePools.
func (mr *MockSpotAPIMockRecorder) ListAutopilotNodePools(ctx, org, cloudspace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAutopilotNodePools", reflect.TypeOf((*MockSpotAPI)(nil).ListAutopilotNodePools), ctx, org, cloudspace)
}

// ListCloudspaces mocks base method.
func (m *MockSpotAPI) ListCloudspaces(ctx context.Context, org string) (*rxtspot.CloudSpaceList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCloudspaces", ctx, org)
	ret0, _ := ret[0].(*rxtspot.CloudSpaceList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCloudspaces indicates an expected call of ListCloudspaces.
func (mr *MockSpotAPIMockRecorder) ListCloudspaces(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCloudspaces", reflect.TypeOf((*MockSpotAPI)(nil).ListCloudspaces), ctx, org)
}

// ListOnDemandNodePools mocks base method.
func (m *MockSpotAPI) ListOnDemandNodePools(ctx context.Context, org, cloudspace string) ([]*rxtspot.OnDemandNodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOnDemandNodePools", ctx, org, cloudspace)
	ret0, _ := ret[0].([]*rxtspot.OnDemandNodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOnDemandNodePools indicates an expected call of ListOnDemandNodePools.
func (mr *MockSpotAPIMockRecorder) ListOnDemandNodePools(ctx, org, cloudspace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOnDemandNodePools", reflect.TypeOf((*MockSpotAPI)(nil).ListOnDemandNodePools), ctx, org, cloudspace)
}

// ListOrganizations mocks base method.
func (m *MockSpotAPI) ListOrganizations(ctx context.Context) ([]rxtspot.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrganizations", ctx)
	ret0, _ := ret[0].([]rxtspot.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrganizations indicates an expected call of ListOrganizations.
func (mr *MockSpotAPIMockRecorder) ListOrganizations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrganizations", reflect.TypeOf((*MockSpotAPI)(nil).ListOrganizations), ctx)
}

// ListRegions mocks base method.
func (m *MockSpotAPI) ListRegions(ctx context.Context) ([]rxtspot.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRegions", ctx)
	ret0, _ := ret[0].([]rxtspot.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRegions indicates an expected call of ListRegions.
func (mr *MockSpotAPIMockRecorder) ListRegions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRegions", reflect.TypeOf((*MockSpotAPI)(nil).ListRegions), ctx)
}

// ListServerClasses mocks base method.
func (m *MockSpotAPI) ListServerClasses(ctx context.Context, region string) (*rxtspot.ServerClassList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServerClasses", ctx, region)
	ret0, _ := ret[0].(*rxtspot.ServerClassList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServerClasses indicates an expected call of ListServerClasses.
func (mr *MockSpotAPIMockRecorder) ListServerClasses(ctx, region any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServerClasses", reflect.TypeOf((*MockSpotAPI)(nil).ListServerClasses), ctx, region)
}

// ListSpotNodePools mocks base method.
func (m *MockSpotAPI) ListSpotNodePools(ctx context.Context, org, cloudspace string) ([]*rxtspot.SpotNodePool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSpotNodePools", ctx, org, cloudspace)
	ret0, _ := ret[0].([]*rxtspot.SpotNodePool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSpotNodePools indicates an expected call of ListSpotNodePools.
func (mr *MockSpotAPIMockRecorder) ListSpotNodePools(ctx, org, cloudspace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSpotNodePools", reflect.TypeOf((*MockSpotAPI)(nil).ListSpotNodePools), ctx, org, cloudspace)
}

// ListVMCloudSpaces mocks base method.
func (m *MockSpotAPI) ListVMCloudSpaces(ctx context.Context, org string) (*rxtspot.VMCloudSpaceList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVMCloudSpaces", ctx, org)
	ret0, _ := ret[0].(*rxtspot.VMCloudSpaceList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVMCloudSpaces indicates an expected call of ListVMCloudSpaces.
func (mr *MockSpotAPIMockRecorder) ListVMCloudSpaces(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVMCloudSpaces", reflect.TypeOf((*MockSpotAPI)(nil).ListVMCloudSpaces), ctx, org)
}

// ListVMPools mocks base method.
func (m *MockSpotAPI) ListVMPools(ctx context.Context, org, vmCloudSpace string) ([]*rxtspot.VMPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVMPools", ctx, org, vmCloudSpace)
	ret0, _ := ret[0].([]*rxtspot.VMPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVMPools indicates an expected call of ListVMPools.
func (mr *MockSpotAPIMockRecorder) ListVMPools(ctx, org, vmCloudSpace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVMPools", reflect.TypeOf((*MockSpotAPI)(nil).ListVMPools), ctx, org, vmCloudSpace)
}

// ListVMSSHKeys mocks base method.
func (m *MockSpotAPI) ListVMSSHKeys(ctx context.Context, org string) (*rxtspot.VMSSHKeyList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVMSSHKeys", ctx, org)
	ret0, _ := ret[0].(*rxtspot.VMSSHKeyList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVMSSHKeys indicates an expected call of ListVMSSHKeys.
func (mr *MockSpotAPIMockRecorder) ListVMSSHKeys(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVMSSHKeys", reflect.TypeOf((*MockSpotAPI)(nil).ListVMSSHKeys), ctx, org)
}

// UpdateAutopilotNodePool mocks base method.
func (m *MockSpotAPI) UpdateAutopilotNodePool(ctx context.Context, org string, pool rxtspot.AutopilotNodePool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAutopilotNodePool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAutopilotNodePool indicates an expected call of UpdateAutopilotNodePool.
func (mr *MockSpotAPIMockRecorder) UpdateAutopilotNodePool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAutopilotNodePool", reflect.TypeOf((*MockSpotAPI)(nil).UpdateAutopilotNodePool), ctx, org, pool)
}

// UpdateOnDemandNodePool mocks base method.
func (m *MockSpotAPI) UpdateOnDemandNodePool(ctx context.Context, org string, pool rxtspot.OnDemandNodePool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOnDemandNodePool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOnDemandNodePool indicates an expected call of UpdateOnDemandNodePool.
func (mr *MockSpotAPIMockRecorder) UpdateOnDemandNodePool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOnDemandNodePool", reflect.TypeOf((*MockSpotAPI)(nil).UpdateOnDemandNodePool), ctx, org, pool)
}

// UpdateSpotNodePool mocks base method.
func (m *MockSpotAPI) UpdateSpotNodePool(ctx context.Context, org string, pool rxtspot.SpotNodePool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSpotNodePool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSpotNodePool indicates an expected call of UpdateSpotNodePool.
func (mr *MockSpotAPIMockRecorder) UpdateSpotNodePool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSpotNodePool", reflect.TypeOf((*MockSpotAPI)(nil).UpdateSpotNodePool), ctx, org, pool)
}

// UpdateVMCloudSpace mocks base method.
func (m *MockSpotAPI) UpdateVMCloudSpace(ctx context.Context, org string, vmcs rxtspot.VMCloudSpace) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVMCloudSpace", ctx, org, vmcs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVMCloudSpace indicates an expected call of UpdateVMCloudSpace.
func (mr *MockSpotAPIMockRecorder) UpdateVMCloudSpace(ctx, org, vmcs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVMCloudSpace", reflect.TypeOf((*MockSpotAPI)(nil).UpdateVMCloudSpace), ctx, org, vmcs)
}

// UpdateVMPool mocks base method.
func (m *MockSpotAPI) UpdateVMPool(ctx context.Context, org string, pool rxtspot.VMPool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVMPool", ctx, org, pool)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVMPool indicates an expected call of UpdateVMPool.
func (mr *MockSpotAPIMockRecorder) UpdateVMPool(ctx, org, pool any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVMPool", reflect.TypeOf((*MockSpotAPI)(nil).UpdateVMPool), ctx, org, pool)
}
