// Code generated by MockGen. DO NOT EDIT.
// Source: cloudspaces.go
//
// Generated by this command:
//
//	mockgen -source=cloudspaces.go -destination=cloudspaces_mock.go -package=rxtspot
//

// Package rxtspot is a generated GoMock package.
package rxtspot
